import type { SlotPreset } from "./types";

const KB = 1024;
const MB = 1024 * 1024;

const IMAGE_TYPES = ["image/jpeg", "image/png", "image/webp"];
const IMAGE_TYPES_WITH_SVG = [...IMAGE_TYPES, "image/svg+xml"];
const VIDEO_TYPES = ["video/mp4", "video/webm"];
const VIDEO_OR_GIF = [...VIDEO_TYPES, "image/gif"];

export const SLOT_PRESETS: SlotPreset[] = [
  // ────────────────────────────────────────────────────────────── Image slots
  {
    id: "project_cover",
    label: "Project cover (16:9)",
    description: "Thumbnail trên home & /portfolio grid.",
    aspect: "16:9",
    recommendedSize: "1280 × 720",
    format: "WebP (q≈82) / JPG mozjpeg",
    maxBytes: 200 * KB,
    maxBytesLabel: "200 KB",
    acceptedTypes: IMAGE_TYPES,
    group: "image",
    tip: "Crop chuẩn 16:9 trước khi upload — đừng để Next.js cover crop mất chủ thể.",
  },
  {
    id: "case_study_hero",
    label: "Case-study hero (21:9)",
    description: "Ảnh full-width đầu trang /portfolio/[slug].",
    aspect: "21:9",
    recommendedSize: "2560 × 1080",
    format: "WebP (q≈80)",
    maxBytes: 500 * KB,
    maxBytesLabel: "500 KB",
    acceptedTypes: IMAGE_TYPES,
    group: "image",
    tip: "Có thể dùng 16:9 (2400 × 1350) nếu nội dung không phù hợp 21:9.",
  },
  // Backward-compat alias (existing media tagged as hero_banner still resolve).
  {
    id: "hero_banner",
    label: "Hero banner (alias case-study hero)",
    description: "Alias cũ của case-study hero — dùng id mới khi tạo mới.",
    aspect: "21:9",
    recommendedSize: "2560 × 1080",
    format: "WebP (q≈80)",
    maxBytes: 500 * KB,
    maxBytesLabel: "500 KB",
    acceptedTypes: IMAGE_TYPES,
    group: "image",
  },
  {
    id: "service_hero",
    label: "Service hero",
    description: "Ảnh full-viewport đầu trang /services/...",
    aspect: "21:9 (≈)",
    recommendedSize: "2400 × 1080",
    format: "WebP (q≈78)",
    maxBytes: 450 * KB,
    maxBytesLabel: "450 KB",
    acceptedTypes: IMAGE_TYPES,
    group: "image",
  },
  {
    id: "service_feature",
    label: "Service feature image",
    description: "Ảnh active trong service-workflow / featured showcase.",
    aspect: "8:5",
    recommendedSize: "1280 × 800",
    format: "WebP (q≈80)",
    maxBytes: 220 * KB,
    maxBytesLabel: "220 KB",
    acceptedTypes: IMAGE_TYPES,
    group: "image",
  },
  {
    id: "mosaic_banner",
    label: "Mosaic banner (3:1)",
    description: "Hàng banner full-width trong portfolio mosaic.",
    aspect: "3:1",
    recommendedSize: "2400 × 800",
    format: "WebP (q≈80)",
    maxBytes: 500 * KB,
    maxBytesLabel: "500 KB",
    acceptedTypes: IMAGE_TYPES,
    group: "image",
  },
  {
    id: "gallery_item",
    label: "Gallery / mosaic tile",
    description: "Ảnh chi tiết trong gallery hoặc tile mosaic 33vw.",
    aspect: "Free",
    recommendedSize: "≥ 1280 px cạnh dài",
    format: "WebP (q≈80) / PNG",
    maxBytes: 250 * KB,
    maxBytesLabel: "250 KB",
    acceptedTypes: IMAGE_TYPES,
    group: "image",
  },
  // ────────────────────────────────────────────────────────────── Icon / logo
  {
    id: "workflow_step",
    label: "Workflow step icon (5:4)",
    description: "Tile nhỏ trong strip workflow (≤ 180 px render).",
    aspect: "5:4",
    recommendedSize: "480 × 384",
    format: "WebP / PNG-24",
    maxBytes: 60 * KB,
    maxBytesLabel: "60 KB",
    acceptedTypes: IMAGE_TYPES,
    group: "icon",
  },
  {
    id: "service_icon",
    label: "Service / studio icon",
    description: "Icon vuông trong studio cards & capabilities grid.",
    aspect: "1:1",
    recommendedSize: "256 × 256",
    format: "SVG ưu tiên, fallback PNG/WebP",
    maxBytes: 40 * KB,
    maxBytesLabel: "40 KB",
    acceptedTypes: IMAGE_TYPES_WITH_SVG,
    group: "icon",
    tip: "SVG (sau SVGOMG) ≤ 5 KB là lý tưởng — scale vô hạn không vỡ.",
  },
  {
    id: "logo",
    label: "Logo header / footer",
    description: "Logo TDG trong header & footer (≈170–260 px W).",
    aspect: "Free",
    recommendedSize: "SVG hoặc 520 × 152",
    format: "SVG / PNG-24 trong suốt",
    maxBytes: 30 * KB,
    maxBytesLabel: "30 KB",
    acceptedTypes: IMAGE_TYPES_WITH_SVG,
    group: "icon",
  },
  {
    id: "partner_logo",
    label: "Partner / brand logo",
    description: "Logo đối tác trong logo grid (260 px W cố định).",
    aspect: "Free",
    recommendedSize: "520 × 200",
    format: "WebP / PNG-24",
    maxBytes: 35 * KB,
    maxBytesLabel: "35 KB",
    acceptedTypes: IMAGE_TYPES,
    group: "icon",
  },
  {
    id: "avatar",
    label: "Avatar review / member",
    description: "Avatar tròn trong testimonials, hero, team.",
    aspect: "1:1",
    recommendedSize: "120 × 120",
    format: "WebP / PNG",
    maxBytes: 25 * KB,
    maxBytesLabel: "25 KB",
    acceptedTypes: IMAGE_TYPES,
    group: "icon",
  },
  {
    id: "marquee",
    label: "Marquee character",
    description: "Tile nhân vật trong character-marquee.",
    aspect: "1:1",
    recommendedSize: "800 × 800",
    format: "WebP (q≈82)",
    maxBytes: 200 * KB,
    maxBytesLabel: "200 KB",
    acceptedTypes: IMAGE_TYPES,
    group: "icon",
  },
  // ────────────────────────────────────────────────────────────── Video / GIF
  {
    id: "hero_video",
    label: "Hero loop video (homepage)",
    description: "Video loop ngắn ở section hero homepage.",
    aspect: "16:9",
    recommendedSize: "1920 × 1080",
    format: "MP4 H.264 + faststart",
    maxBytes: 12 * MB,
    maxBytesLabel: "12 MB · ≤ 8 s",
    acceptedTypes: VIDEO_TYPES,
    group: "video",
    tip: "ffmpeg: -crf 23 -preset slow -pix_fmt yuv420p -movflags +faststart",
  },
  {
    id: "fullgif",
    label: "Case-study fullgif showcase",
    description: "Đoạn animation/clip giới thiệu giữa trang case study.",
    aspect: "16:9",
    recommendedSize: "1920 × 1080",
    format: "MP4 H.264 > WebM > GIF",
    maxBytes: 8 * MB,
    maxBytesLabel: "8 MB · ≤ 6 s",
    acceptedTypes: VIDEO_OR_GIF,
    group: "video",
    tip: "Convert GIF → MP4 trước khi upload — giảm ~80 % dung lượng, vẫn loop được.",
  },
  {
    id: "splash_banner",
    label: "Splash banner cinematic (21:9)",
    description: "Banner cinematic loop ngắn, ratio rộng.",
    aspect: "21:9",
    recommendedSize: "1920 × 820",
    format: "MP4 H.264",
    maxBytes: 5 * MB,
    maxBytesLabel: "5 MB · ≤ 5 s",
    acceptedTypes: VIDEO_OR_GIF,
    group: "video",
  },
  {
    id: "cutscene",
    label: "Cutscene clip / GIF (1280 × 720)",
    description: "Clip ngắn hoặc GIF nhỏ trong section homepage.",
    aspect: "16:9",
    recommendedSize: "1280 × 720",
    format: "WebM VP9 / MP4 / GIF",
    maxBytes: 2 * MB,
    maxBytesLabel: "MP4 ≤ 2 MB / GIF ≤ 4 MB · ≤ 4 s",
    acceptedTypes: VIDEO_OR_GIF,
    group: "video",
  },
  // ───────────────────────────────────────────────────────────────────── Free
  {
    id: "free",
    label: "Free / không xác định",
    description: "Không có ràng buộc cụ thể.",
    aspect: "Free",
    recommendedSize: "—",
    format: "Mọi định dạng image / video",
    maxBytes: 10 * MB,
    maxBytesLabel: "10 MB",
    acceptedTypes: ["image/*", "video/*"],
    group: "other",
  },
];

export function getPresetById(id: string): SlotPreset {
  return SLOT_PRESETS.find((p) => p.id === id) ?? SLOT_PRESETS[SLOT_PRESETS.length - 1];
}

export function formatBytes(bytes: number) {
  if (bytes < KB) return `${bytes} B`;
  if (bytes < MB) return `${(bytes / KB).toFixed(0)} KB`;
  return `${(bytes / MB).toFixed(1)} MB`;
}

export const GROUP_LABEL: Record<NonNullable<SlotPreset["group"]>, string> = {
  image: "Ảnh tĩnh",
  icon: "Logo / Icon / Avatar",
  video: "Video / GIF",
  other: "Khác",
};
