import type { Metadata } from "next";
import LegalPage, { type LegalSection } from "@/components/legal-page";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "How TD Games Studio collects, uses and protects personal data on tdgamestudio.com and in our mobile games and applications.",
};

const INTRO = [
  "This page informs you of our policies regarding the collection, use and disclosure of personal data when you use our website and any mobile game or application published by TD Games, and the choices you have associated with that data.",
  "This policy applies to all games and applications we publish on the Google Play Store and the Apple App Store, unless a specific title links to a different policy of its own.",
  "We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used here have the same meanings as in our Terms of Use.",
];

const SECTIONS: LegalSection[] = [
  {
    title: "Definitions",
    bullets: [
      "Service — the website tdgamestudio.com, including its contact forms, careers pages and any subdomains operated by TD Games, together with every mobile game and application we publish (the “Apps”).",
      "Device Identifiers — identifiers assigned by your mobile operating system, such as the Android Advertising ID, the Apple Identifier for Advertisers (IDFA) and app-instance identifiers used for analytics.",
      "Personal Data — data about a living individual who can be identified from those data, or from those and other information either in our possession or likely to come into our possession.",
      "Usage Data — data collected automatically, either generated by use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).",
      "Cookies — small files stored on your device (computer or mobile device).",
      "Data Controller — the natural or legal person who determines the purposes for which and the manner in which personal information is processed. For the purpose of this Privacy Policy, TD Games is the Data Controller of your Personal Data.",
      "Data Processors (or Service Providers) — any natural or legal person who processes data on behalf of the Data Controller. We may use various Service Providers in order to process your data more effectively.",
      "Data Subject (or User) — any living individual who uses our Service and is the subject of Personal Data.",
    ],
  },
  {
    title: "Information We Collect",
    paragraphs: [
      "We only collect data that you actively give us, plus a minimal amount of technical information needed to keep the Service working.",
      "On the website:",
    ],
    bullets: [
      "Contact details you submit — name, email address, company and the content of your message when you contact us about a project.",
      "Recruitment data — the information, CV, portfolio links and files you submit through our careers pages when you apply for a role.",
      "Usage Data — pages visited, time spent, referring page, browser type, device type and approximate region derived from your IP address.",
      "Cookies and similar technologies used to remember your preferences and to measure aggregate traffic.",
    ],
  },
  {
    title: "Information Our Apps Collect",
    paragraphs: [
      "Our games do not ask you to create an account, and we do not collect your name, email address, phone number or contact list in our Apps. The information below is collected automatically by the Apps and the third-party software development kits they include.",
    ],
    bullets: [
      "Device and technical data — device model, operating system version, language, country, screen resolution and network type.",
      "Device Identifiers — the advertising identifier provided by your operating system and an app-instance identifier used for analytics.",
      "Gameplay and usage data — levels started and completed, session length, in-game progress, feature usage and settings.",
      "Crash and diagnostic data — technical logs generated when the App stops unexpectedly, so we can fix the fault.",
      "Purchase data — a confirmation from the app store that a purchase completed, together with the product identifier. We never receive or store your card number or billing address.",
      "Approximate location — inferred from your IP address at country or region level only. Our Apps do not request GPS or precise location permission.",
    ],
  },
  {
    title: "Recruitment Data",
    paragraphs: [
      "If you apply for a position at TD Games, we process the application materials you submit for the sole purpose of evaluating your candidacy: reviewing your portfolio, contacting you about the role and, where relevant, discussing your application internally within our hiring team.",
      "Application materials are stored in our recruitment database and are accessible only to staff involved in hiring. We retain applications for up to 24 months so that we can consider you for future openings, unless you ask us to delete them sooner. We do not sell, rent or share your application with third parties for their own purposes.",
    ],
  },
  {
    title: "Use of Data",
    bullets: [
      "To provide and maintain our Service.",
      "To respond to enquiries, quotes and project briefs you send us.",
      "To operate our games, save your progress, unlock content you have purchased and display advertising in free-to-play titles.",
      "To diagnose crashes and fix defects in our games.",
      "To evaluate applications submitted through our careers pages.",
      "To notify you about changes to our Service.",
      "To provide customer support.",
      "To gather analysis or valuable information so that we can improve our Service.",
      "To monitor the usage of our Service.",
      "To detect, prevent and address technical issues.",
    ],
  },
  {
    title: "Cookies and Analytics",
    paragraphs: [
      "We use cookies and similar tracking technologies to operate the site and to understand, in aggregate, how it is used. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. If you do not accept cookies, some portions of the Service may not function correctly.",
      "We may use third-party Service Providers to monitor and analyse the use of our Service. These providers process technical and usage information on our behalf and are not permitted to use it for their own purposes. This website does not display third-party advertising and does not run advertising or ad-attribution networks; advertising in our Apps is described separately below.",
    ],
  },
  {
    title: "Analytics in Our Apps",
    paragraphs: [
      "Our Apps use Google Firebase (Analytics and Crashlytics) to understand how the game is played in aggregate and to diagnose crashes. Firebase receives device data, gameplay events, an app-instance identifier and crash logs. We use this to fix bugs, balance difficulty and decide what to build next.",
      "Information about how Google processes this data is available in the Google Privacy Policy at policies.google.com/privacy. You can reset the app-instance identifier by reinstalling the App, and you can clear analytics data by deleting the App from your device.",
    ],
  },
  {
    title: "Advertising",
    paragraphs: [
      "Some of our Apps are free to play and are funded by advertising. We display ads through third-party advertising networks, which may use your Device Identifier and technical data to select and measure the ads you see, including personalised advertising where you have permitted it.",
      "You can control this at any time from your device settings, and your choice is respected by our Apps and by the ad networks we work with.",
    ],
    bullets: [
      "On Android — open Settings, then Google, then Ads, and turn on “Delete advertising ID” or “Opt out of Ads Personalisation”.",
      "On iOS — open Settings, then Privacy & Security, then Tracking, and turn off “Allow Apps to Request to Track”. Our Apps ask for this permission through Apple's App Tracking Transparency prompt and will not track you across other companies' apps unless you allow it.",
      "Opting out does not remove advertising from the App; it means the ads you see are no longer personalised.",
      "Purchasing an ad-removal product, where an App offers one, disables advertising in that App.",
    ],
  },
  {
    title: "In-App Purchases",
    paragraphs: [
      "Purchases inside our Apps are processed entirely by Apple or Google through their own billing systems. Your payment details are handled by the app store under its own privacy policy and are never sent to, seen by, or stored by TD Games.",
      "We receive only a confirmation that a transaction succeeded, along with the product purchased, so that we can unlock the corresponding content. Refunds are handled by the app store, as described in our Terms of Use.",
    ],
  },
  {
    title: "Service Providers and Data Sharing",
    paragraphs: [
      "We rely on a small number of infrastructure providers to run this website: a managed database and authentication platform for storing form submissions and applications, a content delivery network and object storage provider for hosting images and video, and a virtual private server provider for hosting the application itself. Internal notifications about new enquiries and applications may be delivered to our team through a messaging platform.",
      "For our Apps we additionally rely on Google (Firebase Analytics and Crashlytics), the advertising networks that serve ads inside free-to-play titles, and Apple and Google as the operators of their respective app stores and billing systems.",
      "These providers act as Data Processors, may store data outside Vietnam, and are bound by their own agreements to process data only on our instructions. Advertising networks may act as independent controllers of the Device Identifier they receive, in which case their own privacy policies apply. We do not sell your Personal Data.",
    ],
  },
  {
    title: "Data Retention",
    paragraphs: [
      "We keep Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. Enquiry and contact records are retained for as long as needed to manage our relationship with you and to meet legal, accounting or reporting requirements. Recruitment data is retained as described in the Recruitment Data section above. Aggregated Usage Data is retained for statistical purposes.",
      "Analytics and crash data generated by our Apps is retained by our analytics provider for up to 14 months from collection, after which it is deleted automatically. Purchase confirmations are retained for as long as required for accounting and tax purposes.",
    ],
  },
  {
    title: "Your Rights",
    paragraphs: [
      "You may ask us to confirm what Personal Data we hold about you, to correct it if it is inaccurate, to delete it, or to stop processing it. To exercise any of these rights, contact us using the details below. We will respond within a reasonable period, and we may need to verify your identity before acting on the request.",
      "For our Apps: because we do not operate user accounts, the fastest way to stop all further collection is to uninstall the App, which also removes the game data stored on your device. To have the analytics data already associated with your app installation deleted, email us with the name of the game and the date you installed it, and we will process the request with our analytics provider.",
    ],
  },
  {
    title: "Security of Data",
    paragraphs: [
      "The security of your data is important to us, but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.",
    ],
  },
  {
    title: "Children's Privacy",
    paragraphs: [
      "Our Service is not directed to children under the age of 13, and our games are not listed in any app store's children or family programme. We do not knowingly collect personal data from anyone under 13.",
      "If you are a parent or guardian and believe your child has provided us with personal data, please contact us at the address below. If we become aware that we have collected personal data from a child under 13 without verifiable parental consent, we will delete that information from our servers.",
    ],
  },
  {
    title: "Links to Other Websites",
    paragraphs: [
      "Our Service contains links to third-party websites, including client projects, social platforms and portfolio galleries that are not owned or controlled by us. We have no control over, and assume no responsibility for, the content, privacy policies or practices of any third-party websites or services. We strongly advise you to read the privacy policy of every site you visit.",
    ],
  },
  {
    title: "Changes to This Privacy Policy",
    paragraphs: [
      "We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the “Last updated” date above. You are advised to review this Privacy Policy periodically for any changes.",
    ],
  },
  {
    title: "Contact Us",
    paragraphs: [
      "If you have any questions about this Privacy Policy, would like to learn more about why, how and what Personal Data we use, or wish to request its deletion, please contact us at privacy@tdgamestudio.com.",
      "TD GAMES COMPANY LIMITED — Xom Ngoai, Dong Anh Commune, Hanoi City, Vietnam.",
    ],
  },
];

export default function PrivacyPolicyPage() {
  return (
    <LegalPage
      title="Privacy Policy"
      updated="29 August 2026"
      intro={INTRO}
      sections={SECTIONS}
    />
  );
}
